FROM node:16.13.0-alpine as storage

WORKDIR /storage
ENV NODE_ENV production
COPY package.json .
COPY yarn.lock .
RUN yarn install --check-files --cache-folder .ycache && rm -rf .ycache

FROM node:16.13.0-alpine

WORKDIR /app
COPY --from=storage /storage/node_modules node_modules

RUN yarn global add cross-env
ENV NODE_ENV production
COPY dist dist/
COPY build build/
COPY package.json .

CMD [ "yarn", "cms:serve" ]
