/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-brand-header".
 */
export interface Header {
  id: string;
  'Brand Settings': {
    brandLogoType: 'default' | 'lgbt_branded' | 'new_year_branded';
  };
  'solutions-menu': {
    displayName: string;
    targetPage: string | Page;
    image: string | Media;
    id?: string;
  }[];
  Links: {
    'pricing-page': string | Page;
    'professionals-page': string | Page;
    'about-us-page': string | Page;
    'blog-link': string;
    'help-link': string;
  };
  Actions: {
    'Login Link': {
      'Login Text'?: string;
      'Login Url'?: string;
    };
    'Register Button': {
      text: string;
      link: string;
      type: 'primary' | 'secondary' | 'tertiary';
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  layout: (
    | {
        mode: 'dark' | 'light';
        id?: string;
        blockName?: string;
        blockType: 'brand-header';
      }
    | {
        mode: 'dark' | 'light';
        id?: string;
        blockName?: string;
        blockType: 'main-hero';
      }
    | {
        title: {
          desktop: string;
          overrideMobile?: boolean;
          mobile?: string;
          overrideTablet?: boolean;
          tablet?: string;
        };
        description: {
          desktop: string;
          overrideMobile?: boolean;
          mobile?: string;
          overrideTablet?: boolean;
          tablet?: string;
        };
        ctaButton: {
          text: string;
          link: string;
          type: 'primary' | 'secondary' | 'tertiary';
        };
        id?: string;
        blockName?: string;
        blockType: 'get-started-cta';
      }
    | {
        mode: 'dark' | 'light';
        id?: string;
        blockName?: string;
        blockType: 'main-part-1';
      }
    | {
        mode: 'dark' | 'light';
        id?: string;
        blockName?: string;
        blockType: 'main-part-2';
      }
    | {
        mode: 'dark' | 'light';
        id?: string;
        blockName?: string;
        blockType: 'main-part-3';
      }
    | {
        mode: 'dark' | 'light';
        id?: string;
        blockName?: string;
        blockType: 'main-part-4';
      }
    | {
        sectionTag: string;
        title: {
          desktop: string;
          overrideMobile?: boolean;
          mobile?: string;
          overrideTablet?: boolean;
          tablet?: string;
        };
        description: {
          desktop: string;
          overrideMobile?: boolean;
          mobile?: string;
          overrideTablet?: boolean;
          tablet?: string;
        };
        ctaButton: {
          text: string;
          link: string;
          type: 'primary' | 'secondary' | 'tertiary';
        };
        testimonials: {
          quote: string;
          quoter: string;
          quoterTitle: string;
          name: string;
          url: string;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'for-professionals-cta';
      }
    | {
        mode: 'dark' | 'light';
        id?: string;
        blockName?: string;
        blockType: 'line-seperator';
      }
    | {
        mode: 'dark' | 'light';
        id?: string;
        blockName?: string;
        blockType: 'brand-footer';
      }
  )[];
  parent?: string | Page;
  author?: string | User;
  meta: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-about-us".
 */
export interface AboutUs {
  id: string;
  heroSection: {
    heroTitle: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
  };
  mainKPIsSection: {
    kpiList: {
      kpi?: string;
      title?: string;
      description?: string;
      id?: string;
    }[];
  };
  testimonialsSection: {
    title: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    testimonials: {
      quoteTitle: string;
      quote: string;
      quoter: string;
      quoterTitle: string;
      image: string | Media;
      id?: string;
    }[];
  };
  ourPartnersSection: {
    text: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    partners: {
      name: string;
      imageUrl: string;
      id?: string;
    }[];
  };
  joinTheTeamSection: {
    title: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    description: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    ctaButton: {
      text: string;
      link: string;
      type: 'primary' | 'secondary' | 'tertiary';
    };
  };
  _status?: 'draft' | 'published';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-careers-page".
 */
export interface Careers {
  id: string;
  heroSection: {
    title: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    description: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
  };
  lookingForSection: {
    title: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    qualities: {
      title?: string;
      description?: string;
      id?: string;
    }[];
  };
  joinTheTeamSection: {
    title: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    description: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    ctaButton: {
      text: string;
      link: string;
      type: 'primary' | 'secondary' | 'tertiary';
    };
  };
  _status?: 'draft' | 'published';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-pages".
 */
export interface HomePage {
  id: string;
  title: string;
  slug: string;
  heroSection: {
    heroTitle: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    ctaButton: {
      text: string;
      link: string;
      type: 'primary' | 'secondary' | 'tertiary';
    };
    trustedBySection: {
      text: {
        desktop: string;
        overrideMobile?: boolean;
        mobile?: string;
        overrideTablet?: boolean;
        tablet?: string;
      };
    };
  };
  marketingSection: {
    title: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    subtitle: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    elements: {
      title: string;
      description: string;
      learnMoreLink: string;
      icon:
        | '/img/link-icons/artist_bio_link_icon.svg'
        | '/img/link-icons/pre_release_link_icon.svg'
        | '/img/link-icons/released_link_icon.svg'
        | '/img/link-icons/contest_link_icon.svg'
        | '/img/link-icons/tour_link_icon.svg'
        | '/img/link-icons/podcast_link_icon.svg'
        | '/img/link-icons/short_link_icon.svg';
      id?: string;
    }[];
    ctaButton: {
      text: string;
      link: string;
      type: 'primary' | 'secondary' | 'tertiary';
    };
  };
  fanbaseManagementSection: {
    title: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    description: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    tag: string;
    ctaButton: {
      text: string;
      link: string;
      type: 'primary' | 'secondary' | 'tertiary';
    };
  };
  analyticsAndInsightsSection: {
    title: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    description: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    tag: string;
    ctaButton: {
      text: string;
      link: string;
      type: 'primary' | 'secondary' | 'tertiary';
    };
  };
  testimonialsSection: {
    title: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    testimonials: {
      quote: string;
      quoter: string;
      quoterTitle: string;
      image: string | Media;
      quoterLink: {
        name: string;
        url: string;
      };
      id?: string;
    }[];
  };
  forProfessionalsCTASection: {
    sectionTag: string;
    title: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    description: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    ctaButton: {
      text: string;
      link: string;
      type: 'primary' | 'secondary' | 'tertiary';
    };
    testimonials: {
      quote: string;
      quoter: string;
      quoterTitle: string;
      name: string;
      url: string;
      id?: string;
    }[];
  };
  getStartedCTASection: {
    title: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    description: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    ctaButton: {
      text: string;
      link: string;
      type: 'primary' | 'secondary' | 'tertiary';
    };
  };
  meta: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-links-pages".
 */
export interface SolutionLinksPage {
  id: string;
  title: string;
  slug: string;
  heroSection: {
    title: string;
    description: string;
  };
  allLinksComeWith: {
    title: string;
    features: {
      title: {
        desktop: string;
        overrideMobile?: boolean;
        mobile?: string;
        overrideTablet?: boolean;
        tablet?: string;
      };
      description: {
        desktop: string;
        overrideMobile?: boolean;
        mobile?: string;
        overrideTablet?: boolean;
        tablet?: string;
      };
      link: string;
      imageUrl?: string;
      id?: string;
    }[];
  };
  landingPagesSection: {
    features: {
      tag?: string;
      title: {
        desktop: string;
        overrideMobile?: boolean;
        mobile?: string;
        overrideTablet?: boolean;
        tablet?: string;
      };
      description: {
        desktop: string;
        overrideMobile?: boolean;
        mobile?: string;
        overrideTablet?: boolean;
        tablet?: string;
      };
      imageUrl: string;
      topCapabilites: {
        capability?: string;
        id?: string;
      }[];
      isInverse?: boolean;
      padding?: 'small' | 'normal' | 'medium' | 'large';
      ctaButton: {
        text: string;
        link: string;
        type: 'primary' | 'secondary' | 'tertiary';
      };
      id?: string;
    }[];
  };
  allLinksComeWithMore: {
    title: string;
    features: {
      title: {
        desktop: string;
        overrideMobile?: boolean;
        mobile?: string;
        overrideTablet?: boolean;
        tablet?: string;
      };
      description: {
        desktop: string;
        overrideMobile?: boolean;
        mobile?: string;
        overrideTablet?: boolean;
        tablet?: string;
      };
      link: string;
      id?: string;
    }[];
  };
  youShouldAlsoCheckOut: {
    title: string;
    features: {
      title: {
        desktop: string;
        overrideMobile?: boolean;
        mobile?: string;
        overrideTablet?: boolean;
        tablet?: string;
      };
      description: {
        desktop: string;
        overrideMobile?: boolean;
        mobile?: string;
        overrideTablet?: boolean;
        tablet?: string;
      };
      link: string;
      imageUrl?: string;
      id?: string;
    }[];
  };
  getStartedCTASection: {
    title: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    description: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    ctaButton: {
      text: string;
      link: string;
      type: 'primary' | 'secondary' | 'tertiary';
    };
  };
  meta: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-audience-pages".
 */
export interface SolutionAudiencePage {
  id: string;
  title: string;
  slug: string;
  heroSection: {
    title: string;
    description: string;
  };
  featuresSection: {
    features: {
      tag?: string;
      title: {
        desktop: string;
        overrideMobile?: boolean;
        mobile?: string;
        overrideTablet?: boolean;
        tablet?: string;
      };
      description: {
        desktop: string;
        overrideMobile?: boolean;
        mobile?: string;
        overrideTablet?: boolean;
        tablet?: string;
      };
      imageUrl: string;
      topCapabilites: {
        capability?: string;
        id?: string;
      }[];
      isInverse?: boolean;
      padding?: 'small' | 'normal' | 'medium' | 'large';
      ctaButton: {
        text: string;
        link: string;
        type: 'primary' | 'secondary' | 'tertiary';
      };
      id?: string;
    }[];
  };
  youShouldAlsoCheckOut: {
    title: string;
    features: {
      title: {
        desktop: string;
        overrideMobile?: boolean;
        mobile?: string;
        overrideTablet?: boolean;
        tablet?: string;
      };
      description: {
        desktop: string;
        overrideMobile?: boolean;
        mobile?: string;
        overrideTablet?: boolean;
        tablet?: string;
      };
      link: string;
      imageUrl?: string;
      id?: string;
    }[];
  };
  getStartedCTASection: {
    title: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    description: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    ctaButton: {
      text: string;
      link: string;
      type: 'primary' | 'secondary' | 'tertiary';
    };
  };
  meta: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solution-analytics-pages".
 */
export interface SolutionAnalyticsPage {
  id: string;
  title: string;
  slug: string;
  heroSection: {
    title: string;
    description: string;
  };
  featuresSection: {
    features: {
      tag?: string;
      title: {
        desktop: string;
        overrideMobile?: boolean;
        mobile?: string;
        overrideTablet?: boolean;
        tablet?: string;
      };
      description: {
        desktop: string;
        overrideMobile?: boolean;
        mobile?: string;
        overrideTablet?: boolean;
        tablet?: string;
      };
      imageUrl: string;
      topCapabilites: {
        capability?: string;
        id?: string;
      }[];
      isInverse?: boolean;
      padding?: 'small' | 'normal' | 'medium' | 'large';
      id?: string;
    }[];
  };
  youShouldAlsoCheckOut: {
    title: string;
    features: {
      title: {
        desktop: string;
        overrideMobile?: boolean;
        mobile?: string;
        overrideTablet?: boolean;
        tablet?: string;
      };
      description: {
        desktop: string;
        overrideMobile?: boolean;
        mobile?: string;
        overrideTablet?: boolean;
        tablet?: string;
      };
      link: string;
      imageUrl?: string;
      id?: string;
    }[];
  };
  getStartedCTASection: {
    title: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    description: {
      desktop: string;
      overrideMobile?: boolean;
      mobile?: string;
      overrideTablet?: boolean;
      tablet?: string;
    };
    ctaButton: {
      text: string;
      link: string;
      type: 'primary' | 'secondary' | 'tertiary';
    };
  };
  meta: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-pages".
 */
export interface PricingPage {
  id: string;
  title: string;
  slug: string;
  hero: {
    title: string;
    description: string;
  };
  pricingTiers: {
    artistTiers: {
      pricingPlans: {
        planOneSummary: {
          planName: string;
          planMonthlyPrice: string;
          planYearlyPrice: string;
          isCustomPrice?: boolean;
          planDescription: string;
          ctaButton: {
            text: string;
            link: string;
            type: 'primary' | 'secondary' | 'tertiary';
          };
          planFeatures: {
            feature: string;
            id?: string;
          }[];
        };
        planTwoSummary: {
          planName: string;
          planMonthlyPrice: string;
          planYearlyPrice: string;
          isCustomPrice?: boolean;
          planDescription: string;
          ctaButton: {
            text: string;
            link: string;
            type: 'primary' | 'secondary' | 'tertiary';
          };
          planFeatures: {
            feature: string;
            id?: string;
          }[];
        };
        planThreeSummary: {
          planName: string;
          planMonthlyPrice: string;
          planYearlyPrice: string;
          isCustomPrice?: boolean;
          planDescription: string;
          ctaButton: {
            text: string;
            link: string;
            type: 'primary' | 'secondary' | 'tertiary';
          };
          planFeatures: {
            feature: string;
            id?: string;
          }[];
        };
        planComparison: {
          featuresComparison: {
            feature: string;
            tooltip: string;
            link: string;
            planValues: {
              planOne: string;
              planTwo: string;
              planThree: string;
            };
            id?: string;
            blockName?: string;
            blockType: 'feature-comparison-basic';
          }[];
          id?: string;
          blockName?: string;
          blockType: 'pricing-section';
        }[];
      };
    };
    businessTiers: {
      pricingPlans: {
        planOneSummary: {
          planName: string;
          planMonthlyPrice: string;
          planYearlyPrice: string;
          isCustomPrice?: boolean;
          planDescription: string;
          ctaButton: {
            text: string;
            link: string;
            type: 'primary' | 'secondary' | 'tertiary';
          };
          planFeatures: {
            feature: string;
            id?: string;
          }[];
        };
        planTwoSummary: {
          planName: string;
          planMonthlyPrice: string;
          planYearlyPrice: string;
          isCustomPrice?: boolean;
          planDescription: string;
          ctaButton: {
            text: string;
            link: string;
            type: 'primary' | 'secondary' | 'tertiary';
          };
          planFeatures: {
            feature: string;
            id?: string;
          }[];
        };
        planThreeSummary: {
          planName: string;
          planMonthlyPrice: string;
          planYearlyPrice: string;
          isCustomPrice?: boolean;
          planDescription: string;
          ctaButton: {
            text: string;
            link: string;
            type: 'primary' | 'secondary' | 'tertiary';
          };
          planFeatures: {
            feature: string;
            id?: string;
          }[];
        };
        planComparison: {
          featuresComparison: {
            feature: string;
            tooltip: string;
            link: string;
            planValues: {
              planOne: string;
              planTwo: string;
              planThree: string;
            };
            id?: string;
            blockName?: string;
            blockType: 'feature-comparison-basic';
          }[];
          id?: string;
          blockName?: string;
          blockType: 'pricing-section';
        }[];
      };
    };
  };
  meta: {
    title?: string;
    description?: string;
    image?: string | Media;
  };
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
